CREATE OR REPLACE TABLE stg_patients AS
SELECT
    CAST(age AS INTEGER) AS age,
    TRY_CAST(number_of_sexual_partners AS DOUBLE) AS number_of_sexual_partners,
    TRY_CAST(first_sexual_intercourse AS DOUBLE) AS first_sexual_intercourse,
    TRY_CAST(num_of_pregnancies AS DOUBLE) AS num_of_pregnancies,
    TRY_CAST(smokes AS INTEGER) AS smokes,
    TRY_CAST(smokes_years AS DOUBLE) AS smokes_years,
    TRY_CAST(smokes_packs_year AS DOUBLE) AS smokes_packs_year,
    TRY_CAST(hormonal_contraceptives AS INTEGER) AS hormonal_contraceptives,
    TRY_CAST(hormonal_contraceptives_years AS DOUBLE) AS hormonal_contraceptives_years,
    TRY_CAST(iud AS INTEGER) AS iud,
    TRY_CAST(iud_years AS DOUBLE) AS iud_years,
    TRY_CAST(stds AS INTEGER) AS stds,
    TRY_CAST(stds_number AS DOUBLE) AS stds_number,
    TRY_CAST(stds_condylomatosis AS INTEGER) AS stds_condylomatosis,
    TRY_CAST(stds_cervical_condylomatosis AS INTEGER) AS stds_cervical_condylomatosis,
    TRY_CAST(stds_vaginal_condylomatosis AS INTEGER) AS stds_vaginal_condylomatosis,
    TRY_CAST(stds_vulvo_perineal_condylomatosis AS INTEGER) AS stds_vulvo_perineal_condylomatosis,
    TRY_CAST(stds_syphilis AS INTEGER) AS stds_syphilis,
    TRY_CAST(stds_pelvic_inflammatory_disease AS INTEGER) AS stds_pelvic_inflammatory_disease,
    TRY_CAST(stds_genital_herpes AS INTEGER) AS stds_genital_herpes,
    TRY_CAST(stds_molluscum_contagiosum AS INTEGER) AS stds_molluscum_contagiosum,
    TRY_CAST(stds_aids AS INTEGER) AS stds_aids,
    TRY_CAST(stds_hiv AS INTEGER) AS stds_hiv,
    TRY_CAST(stds_hepatitis_b AS INTEGER) AS stds_hepatitis_b,
    TRY_CAST(stds_hpv AS INTEGER) AS stds_hpv,
    TRY_CAST(stds_number_of_diagnosis AS DOUBLE) AS stds_number_of_diagnosis,
    TRY_CAST(stds_time_since_first_diagnosis AS DOUBLE) AS stds_time_since_first_diagnosis,
    TRY_CAST(stds_time_since_last_diagnosis AS DOUBLE) AS stds_time_since_last_diagnosis,
    TRY_CAST(dx_cancer AS INTEGER) AS dx_cancer,
    TRY_CAST(dx_cin AS INTEGER) AS dx_cin,
    TRY_CAST(dx_hpv AS INTEGER) AS dx_hpv,
    TRY_CAST(dx AS INTEGER) AS dx,
    TRY_CAST(hinselmann AS INTEGER) AS hinselmann,
    TRY_CAST(schiller AS INTEGER) AS schiller,
    TRY_CAST(cytology AS INTEGER) AS cytology,
    TRY_CAST(biopsy AS INTEGER) AS biopsy,
    CASE WHEN TRY_CAST(smokes AS INTEGER) = 1 THEN 1 ELSE 0 END AS is_smoker,
    CASE WHEN TRY_CAST(stds AS INTEGER) = 1 OR TRY_CAST(stds_number AS DOUBLE) > 0 THEN 1 ELSE 0 END AS has_std_history
FROM raw_cervical_cancer;
